{
    release = {20, 18},
    releaseType = "development",
    spaceRequirement = 108000,
    releaseDate = {
        m = 5,
        d = 1,
        y = 2020
    },
    directories = {
        "/bin/",
        "/bin/themes",
        "/bin/ui",
        "/boot/",
        "/etc/",
        "/etc/menu/",
        "/home/",
        "/lib/"
    },
    files = {
        "/bin/themes/classic.theme",
        "/bin/themes/dark.theme",
        "/bin/ui/fancyshutdown.lua",
        "/bin/ui/about.lua",
        "/bin/ui/login.lua",
        "/bin/ui/menu.lua",
        "/bin/ui/run.lua",
        "/bin/ui/shutdown.lua",
        "/bin/ui/titlebar.lua",
        "/bin/ui/tskmgr.lua",
        "/bin/ui/settings.lua",
        "/bin/kernel.lua",
        "/bin/shell.lua",
        "/boot/files.cfg",
        "/boot/package.path",
        "/boot/sys.path",
        "/etc/menu/pinned.cfg",
        "/etc/accounts.cfg",
        "/etc/theme.cfg",
        "/lib/util/file.lua",
        "/lib/util/general.lua",
        "/lib/util/http.lua",
        "/lib/util/init.lua",
        "/lib/util/json.lua",
        "/lib/util/math.lua",
        "/lib/json.lua",
        "/lib/nfte.lua",
        "/lib/sha256.lua",
        "/lib/textbox.lua",
        "/lib/scrollwindow.lua",
        "/lib/draw.lua",
        "/startup.lua"
    }
}
